// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP6nczudW_paSSqkiu9Y_0-7On44_mlO8',
    appId: '1:870712040446:web:df189019dadaae2af0beaf',
    messagingSenderId: '870712040446',
    projectId: 'hospital-7aa99',
    authDomain: 'hospital-7aa99.firebaseapp.com',
    storageBucket: 'hospital-7aa99.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjUbAY3WzQD6D_o7OLGN_D34Yhs4j2ftU',
    appId: '1:870712040446:android:bdfdd126a90e6be3f0beaf',
    messagingSenderId: '870712040446',
    projectId: 'hospital-7aa99',
    storageBucket: 'hospital-7aa99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOhUmm_hXeL2OIcp9BqEJfcL9a__44OVQ',
    appId: '1:870712040446:ios:fd77a3c62ab2f57bf0beaf',
    messagingSenderId: '870712040446',
    projectId: 'hospital-7aa99',
    storageBucket: 'hospital-7aa99.appspot.com',
    iosBundleId: 'com.example.hospital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOhUmm_hXeL2OIcp9BqEJfcL9a__44OVQ',
    appId: '1:870712040446:ios:fd77a3c62ab2f57bf0beaf',
    messagingSenderId: '870712040446',
    projectId: 'hospital-7aa99',
    storageBucket: 'hospital-7aa99.appspot.com',
    iosBundleId: 'com.example.hospital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP6nczudW_paSSqkiu9Y_0-7On44_mlO8',
    appId: '1:870712040446:web:8bbfa4c9e27e9817f0beaf',
    messagingSenderId: '870712040446',
    projectId: 'hospital-7aa99',
    authDomain: 'hospital-7aa99.firebaseapp.com',
    storageBucket: 'hospital-7aa99.appspot.com',
  );
}
